name: weekPluginDeploy

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
          
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'
                
    - name: Check Service
      uses: actions/setup-go@v5
      with: 
        go-version: '1.21.5'
            
    - name: Build
      run: sudo go build -buildmode=plugin -trimpath -o weeks.plugin main.go
      
    - name: CopyFile
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.IP_ADDRESS}}
        USER_NAME: ${{secrets.USER_NAME}}
      run: |      
        sudo echo "$PRIVATE_KEY" > private_key.pem
        sudo chmod 600 private_key.pem
        sudo scp -o StrictHostKeyChecking=no -i private_key.pem weeks.plugin $USER_NAME@$HOSTNAME:/home/$USER_NAME/weeks.plugin.tmp
        

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    
    - name: Deploy weeksPlugin to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.IP_ADDRESS}}
        USER_NAME: ${{secrets.USER_NAME}}
      run: |      
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME '
          sudo systemctl stop sunissup
          sudo mv /home/'$USER_NAME'/weeks.plugin.tmp /opt/sunissUp/plugins/weeks.plugin
          sudo chmod +x /opt/sunissUp/plugins/weeks.plugin
          sudo systemctl start sunissup
          echo "Weeks Plugin Deployed"
        '
