export const DiagnosticTable = {
    'N/A': 'N/A',
    F064: 'Anxiety disorder due to known physiological condition',
    F068: 'Other specified mental disorders due to known physiological condition',
    F070: 'Neurological System - Head and Neck',
    F0789: 'Other personality and behavioral disorders due to known physiological condition',
    F09: 'Unspecified mental disorder due to known physiological condition',
    F200: 'Paranoid schizophrenia',
    F201: 'Disorganized schizophrenia',
    F202: 'Catatonic schizophrenia',
    F203: 'Undifferentiated schizophrenia',
    F205: 'Residual schizophrenia',
    F2081: 'Schizophreniform disorder',
    F2089: 'Other schizophrenia',
    F209: 'Schizophrenia, unspecified',
    F21: 'Schizotypal disorder',
    F22: 'Delusional disorders',
    F23: 'Brief psychotic disorder',
    F24: 'Shared psychotic disorder',
    F250: 'Schizoaffective disorder, bipolar type',
    F251: 'Schizoaffective disorder, depressive type',
    F258: 'Other schizoaffective disorders',
    F259: 'Schizoaffective disorder, unspecified',
    F28: 'Other psychotic disorder not due to a substance or known physiological condition',
    F29: 'Unspecified psychosis not due to a substance or known physiological condition',
    F3010: 'Manic episode without psychotic symptoms, unspecified',
    F3011: 'Manic episode without psychotic symptoms, mild',
    F3012: 'Manic episode without psychotic symptoms, moderate',
    F3013: 'Manic episode, severe, without psychotic symptoms',
    F302: 'Manic episode, severe with psychotic symptoms',
    F303: 'Manic episode in partial remission',
    F304: 'Manic episode in full remission',
    F309: 'Manic episode, unspecified',
    F310: 'Bipolar disorder, current episode hypomanic',
    F3110: 'Bipolar disorder, current episode manic without psychotic features, unspecified',
    F3111: 'Bipolar disorder, current episode manic without psychotic features, mild',
    F3112: 'Bipolar disorder, current episode manic without psychotic features, moderate',
    F3113: 'Bipolar disorder, current episode manic without psychotic features, severe',
    F312: 'Bipolar disorder, current episode manic severe with psychotic features',
    F3130: 'Bipolar disorder, current episode depressed, mild or moderate severity, unspecified',
    F3131: 'Bipolar disorder, current episode depressed, mild',
    F3132: 'Bipolar disorder, current episode depressed, moderate',
    F314: 'Bipolar disorder, current episode depressed, severe, without psychotic features',
    F315: 'Bipolar disorder, current episode depressed, severe, with psychotic features',
    F3160: 'Bipolar disorder, current episode mixed, unspecified',
    F3161: 'Bipolar disorder, current episode mixed, mild',
    F3162: 'Bipolar disorder, current episode mixed, moderate',
    F3163: 'Bipolar disorder, current episode mixed, severe, without psychotic features',
    F3164: 'Bipolar disorder, current episode mixed, severe, with psychotic features',
    F3170: 'Bipolar disorder, currently in remission, most recent episode unspecified',
    F3171: 'Bipolar disorder, in partial remission, most recent episode hypomanic',
    F3172: 'Bipolar disorder, in full remission, most recent episode hypomanic',
    F3173: 'Bipolar disorder, in partial remission, most recent episode manic',
    F3174: 'Bipolar disorder, in full remission, most recent episode manic',
    F3175: 'Bipolar disorder, in partial remission, most recent episode depressed',
    F3176: 'Bipolar disorder, in full remission, most recent episode depressed',
    F3177: 'Bipolar disorder, in partial remission, most recent episode mixed',
    F3178: 'Bipolar disorder, in full remission, most recent episode mixed',
    F3181: 'Bipolar II disorder',
    F3189: 'Other bipolar disorder',
    F319: 'Bipolar disorder, unspecified',
    F320: 'Major depressive disorder, single episode, mild',
    F321: 'Major depressive disorder, single episode, moderate',
    F322: 'Major depressive disorder, single episode, severe without psychotic features',
    F323: 'Major depressive disorder, single episode, severe with psychotic features',
    F324: 'Major depressive disorder, single episode, in partial remission',
    F325: 'Major depressive disorder, single episode, in full remission',
    F3281: 'Premenstrual dysphoric disorder',
    F3289: 'Other specified depressive episodes',
    F329: 'Major depressive disorder, single episode, unspecified',
    F32A: 'Depression, unspecified',
    F330: 'Major depressive disorder, recurrent, mild',
    F331: 'Major depressive disorder, recurrent, moderate',
    F332: 'Major depressive disorder, recurrent severe without psychotic features',
    F333: 'Major depressive disorder, recurrent, severe with psychotic symptoms',
    F3340: 'Major depressive disorder, recurrent, in remission, unspecified',
    F3341: 'Major depressive disorder, recurrent, in partial remission',
    F3342: 'Major depressive disorder, recurrent, in full remission',
    F338: 'Other recurrent depressive disorders',
    F339: 'Major depressive disorder, recurrent, unspecified',
    F340: 'Cyclothymic disorder',
    F341: 'Dysthymic disorder',
    F3481: 'Disruptive mood dysregulation disorder',
    F3489: 'Other specified persistent mood disorders',
    F349: 'Persistent mood [affective] disorder, unspecified',
    F39: 'Unspecified mood [affective] disorder',
    F4000: 'Agoraphobia, unspecified',
    F4001: 'Agoraphobia with panic disorder',
    F4002: 'Agoraphobia without panic disorder',
    F4010: 'Social phobia, unspecified',
    F4011: 'Social phobia, generalized',
    F40210: 'Arachnophobia',
    F40218: 'Other animal type phobia',
    F40220: 'Fear of thunderstorms',
    F40228: 'Other natural environment type phobia',
    F40230: 'Fear of blood',
    F40231: 'Fear of injections and transfusions',
    F40232: 'Fear of other medical care',
    F40233: 'Fear of injury',
    F40240: 'Claustrophobia',
    F40241: 'Acrophobia',
    F40242: 'Fear of bridges',
    F40243: 'Fear of flying',
    F40248: 'Other situational type phobia',
    F40290: 'Androphobia',
    F40291: 'Gynephobia',
    F40298: 'Other specified phobia',
    F408: 'Other phobic anxiety disorders',
    F409: 'Phobic anxiety disorder, unspecified',
    F410: 'Panic disorder [episodic paroxysmal anxiety]',
    F411: 'Generalized anxiety disorder',
    F413: 'Other mixed anxiety disorders',
    F418: 'Other specified anxiety disorders',
    F419: 'Anxiety disorder, unspecified',
    F422: 'Mixed obsessional thoughts and acts',
    F423: 'Hoarding disorder',
    F424: 'Excoriation (skin-picking) disorder',
    F428: 'Other obsessive-compulsive disorder',
    F429: 'Obsessive-compulsive disorder, unspecified',
    F430: 'Acute stress reaction',
    F4310: 'Post-traumatic stress disorder, unspecified',
    F4311: 'Post-traumatic stress disorder, acute',
    F4312: 'Post-traumatic stress disorder, chronic',
    F4320: 'Adjustment disorder, unspecified',
    F4321: 'Adjustment disorder with depressed mood',
    F4322: 'Adjustment disorder with anxiety',
    F4323: 'Adjustment disorder with mixed anxiety and depressed mood',
    F4324: 'Adjustment disorder with disturbance of conduct',
    F4325: 'Adjustment disorder with mixed disturbance of emotions and conduct',
    F4329: 'Adjustment disorder with other symptoms',
    F438: 'Other reactions to severe stress',
    F439: 'Reaction to severe stress, unspecified',
    F440: 'Dissociative amnesia',
    F441: 'Dissociative fugue',
    F442: 'Dissociative stupor',
    F444: 'Conversion disorder with motor symptom or deficit',
    F445: 'Conversion disorder with seizures or convulsions',
    F446: 'Conversion disorder with sensory symptom or deficit',
    F447: 'Conversion disorder with mixed symptom presentation',
    F4481: 'Dissociative identity disorder',
    F4489: 'Other dissociative and conversion disorders',
    F449: 'Dissociative and conversion disorder, unspecified',
    F450: 'Somatization disorder',
    F451: 'Undifferentiated somatoform disorder',
    F4520: 'Hypochondriacal disorder, unspecified',
    F4521: 'Hypochondriasis',
    F4522: 'Body dysmorphic disorder',
    F4529: 'Other hypochondriacal disorders',
    F4541: 'Pain disorder exclusively related to psychological factors',
    F4542: 'Pain disorder with related psychological factors',
    F458: 'Other somatoform disorders',
    F459: 'Somatoform disorder, unspecified',
    F481: 'Depersonalization-derealization syndrome',
    F482: 'Pseudobulbar affect',
    F488: 'Other specified nonpsychotic mental disorders',
    F489: 'Nonpsychotic mental disorder, unspecified',
    F5000: 'Anorexia nervosa, unspecified',
    F5001: 'Anorexia nervosa, restricting type',
    F5002: 'Anorexia nervosa, binge eating/purging type',
    F502: 'Bulimia nervosa',
    F5081: 'Binge eating disorder',
    F5082: 'Avoidant/restrictive food intake disorder',
    F5089: 'Other specified eating disorder',
    F509: 'Eating disorder, unspecified',
    F5101: 'Primary insomnia',
    F5102: 'Adjustment insomnia',
    F5103: 'Paradoxical insomnia',
    F5104: 'Psychophysiologic insomnia',
    F5105: 'Insomnia due to other mental disorder',
    F5109: 'Other insomnia not due to a substance or known physiological condition',
    F5111: 'Primary hypersomnia',
    F5112: 'Insufficient sleep syndrome',
    F5113: 'Hypersomnia due to other mental disorder',
    F5119: 'Other hypersomnia not due to a substance or known physiological condition',
    F513: 'Sleepwalking [somnambulism]',
    F514: 'Sleep terrors [night terrors]',
    F515: 'Nightmare disorder',
    F518: 'Other sleep disorders not due to a substance or known physiological condition',
    F519: 'Sleep disorder not due to a substance or known physiological condition, unspecified',
    F530: 'Postpartum depression',
    F531: 'Puerperal psychosis',
    F54: 'Psychological and behavioral factors associated with disorders or diseases classified elsewhere',
    F600: 'Paranoid personality disorder',
    F601: 'Schizoid personality disorder',
    F602: 'Antisocial personality disorder',
    F603: 'Borderline personality disorder',
    F604: 'Histrionic personality disorder',
    F605: 'Obsessive-compulsive personality disorder',
    F606: 'Avoidant personality disorder',
    F607: 'Dependent personality disorder',
    F6081: 'Narcissistic personality disorder',
    F6089: 'Other specific personality disorders',
    F609: 'Personality disorder, unspecified',
    F630: 'Pathological gambling',
    F631: 'Pyromania',
    F632: 'Kleptomania',
    F633: 'Trichotillomania',
    F6381: 'Intermittent explosive disorder',
    F6389: 'Other impulse disorders',
    F639: 'Impulse disorder, unspecified',
    F640: 'Transsexualism',
    F641: 'Dual role transvestism',
    F642: 'Gender identity disorder of childhood',
    F648: 'Other gender identity disorders',
    F649: 'Gender identity disorder, unspecified',
    F6810: 'Factitious disorder imposed on self, unspecified',
    F6811: 'Factitious disorder imposed on self, with predominantly psychological signs and symptoms',
    F6812: 'Factitious disorder imposed on self, with predominantly physical signs and symptoms',
    F6813: 'Factitious disorder imposed on self, with combined psychological and physical signs and symptoms',
    F68A: 'Factitious disorder imposed on another',
    F69: 'Unspecified disorder of adult personality and behavior',
    F8082: 'Social pragmatic communication disorder',
    F900: 'Attention-deficit hyperactivity disorder, predominantly inattentive type',
    F901: 'Attention-deficit hyperactivity disorder, predominantly hyperactive type',
    F902: 'Attention-deficit hyperactivity disorder, combined type',
    F908: 'Attention-deficit hyperactivity disorder, other type',
    F909: 'Attention-deficit hyperactivity disorder, unspecified type',
    F910: 'Conduct disorder confined to family context',
    F911: 'Conduct disorder, childhood-onset type',
    F912: 'Conduct disorder, adolescent-onset type',
    F913: 'Oppositional defiant disorder',
    F918: 'Other conduct disorders',
    F919: 'Conduct disorder, unspecified',
    F930: 'Separation anxiety disorder of childhood',
    F938: 'Other childhood emotional disorders',
    F939: 'Childhood emotional disorder, unspecified',
    F940: 'Selective mutism',
    F941: 'Reactive attachment disorder of childhood',
    F942: 'Disinhibited attachment disorder of childhood',
    F948: 'Other childhood disorders of social functioning',
    F949: 'Childhood disorder of social functioning, unspecified',
    F980: 'Enuresis not due to a substance or known physiological condition',
    F981: 'Encopresis not due to a substance or known physiological condition',
    F9821: 'Rumination disorder of infancy',
    F9829: 'Other feeding disorders of infancy and early childhood',
    F983: 'Pica of infancy and childhood',
    F984: 'Stereotyped movement disorders',
    F985: 'Adult onset fluency disorder',
    F988: 'Other specified behavioral and emotional disorders with onset usually occurring in childhood and adolescence',
    F989: 'Unspecified behavioral and emotional disorders with onset usually occurring in childhood and adolescence',
    F99: 'Mental disorder, not otherwise specified',
    O906: 'Postpartum mood disturbance',
    T7402xa: 'Child neglect or abandonment, confirmed, initial encounter',
    T7402XD: 'Child neglect or abandonment, confirmed, subsequent encounter',
    T7402XS: 'Child neglect or abandonment, confirmed, sequela',
    T7412XA: 'Child physical abuse, confirmed, initial encounter',
    T7412XD: 'Child physical abuse, confirmed, subsequent encounter',
    T7412XS: 'Child physical abuse, confirmed, sequela',
    T7422XA: 'Child sexual abuse, confirmed, initial encounter',
    T7422XD: 'Child sexual abuse, confirmed, subsequent encounter',
    T7422xs: 'Child sexual abuse, confirmed, sequela',
    T7452XA: 'Child sexual exploitation, confirmed, initial encounter',
    T7452XD: 'Child sexual exploitation, confirmed, subsequent encounter',
    T7452XS: 'Child sexual exploitation, confirmed, sequela',
    T7462XA: 'Child forced labor exploitation, confirmed, initial encounter',
    T7462XD: 'Child forced labor exploitation, confirmed, subsequent encounter',
    T7462XS: 'Child forced labor exploitation, confirmed, sequela',
    T7602XA: 'Child neglect or abandonment, suspected, initial encounter',
    T7602xd: 'Child neglect or abandonment, suspected, subsequent encounter',
    T7602XS: 'Child neglect or abandonment, suspected, sequela',
    T7612XA: 'Child physical abuse, suspected, initial encounter',
    T7612XD: 'Child physical abuse, suspected, subsequent encounter',
    T7612XS: 'Child physical abuse, suspected, sequela',
    T7622XA: 'Child sexual abuse, suspected, initial encounter',
    T7622XD: 'Child sexual abuse, suspected, subsequent encounter',
    T7622XS: 'Child sexual abuse, suspected, sequela',
    T7652xd: 'Child sexual exploitation, suspected, subsequent encounter',
    T7652XS: 'Child sexual exploitation, suspected, sequela',
    T7662XA: 'Child forced labor exploitation, suspected, initial encounter',
    T7662XD: 'Child forced labor exploitation, suspected, subsequent encounter',
    T7662XS: 'Child forced labor exploitation, suspected, sequela'
};