package system

import (
	"encoding/json"

	"os"

	"github.com/HoteiApp/sunnix/backend/models"
)

func JsonRead() models.AutogeneratedSupervisions {
	byteValue, _ := os.ReadFile(Path + "/tools/supervisions.json")
	var result models.AutogeneratedSupervisions
	_ = json.Unmarshal(byteValue, &result)
	return result
}
