package models

import "gorm.io/gorm"

type SupervisionsDomain struct {
	gorm.Model
	Order  int    `json:"order"`
	Domain string `json:"domain"`
	Active bool   `json:"active"`
}

type SupervisionsTopics struct {
	gorm.Model
	Domain int     `json:"domain"`
	Title  string  `json:"title"`
	Hour   float64 `json:"hour"`
	Order  int     `json:"order"`
}

type SupervisionsUser struct {
	gorm.Model
	User          int    `json:"user"`
	Topic         int    `json:"topic"`
	Date          string `json:"date"`
	DataTcm       string `json:"date_tcm"`
	SignatureTcm  string `json:"-"` // Siganture
	DataTcms      string `json:"date_tcms"`
	SignatureTcms string `json:"-"` // Siganture
	Completed     bool   `json:"completed"`
}

type AutogeneratedSupervisions struct {
	Supervisions []struct {
		Order  int    `json:"order"`
		Domain string `json:"domain"`
		Active bool   `json:"active"`
		Topics []struct {
			Title string  `json:"title"`
			Hour  float64 `json:"hour"`
			Order int     `json:"order"`
		} `json:"topics"`
	} `json:"supervisions"`
}
type SupervisionsOut struct {
	ID     uint                 `json:"id"`
	Order  int                  `json:"order"`
	Domain string               `json:"domain"`
	Active bool                 `json:"active"`
	Topics []SupervisionsTopics `json:"topics"`
}

type SupervisionsTCMOut struct {
	ID            uint    `json:"id"`
	User          int     `json:"user"`
	DomainID      int     `json:"domain_id"`
	Domain        string  `json:"domain"`
	TopicID       int     `json:"topic_id"`
	Title         string  `json:"title"`
	Hour          float64 `json:"hour"`
	Order         int     `json:"order"`
	Date          string  `json:"date"`
	DataTcm       string  `json:"date_tcm"`
	SignatureTcm  string  `json:"signature_tcm"` // Siganture
	DataTcms      string  `json:"date_tcms"`
	SignatureTcms string  `json:"signature_tcms"` // Siganture
	Completed     bool    `json:"completed"`
}
