# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# #

name: GoDeploy2EC2

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
          
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'
                
    - name: Check Service
      uses: actions/setup-go@v5
      with: 
        go-version: '1.21.5'
            
    - name: Build
      run: sudo go build -trimpath -o sunissup main.go
      
    - name: CopyFile and folder
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.IP_ADDRESS}}
        USER_NAME: ${{secrets.USER_NAME}}
      run: |      
        sudo echo "$PRIVATE_KEY" > private_key.pem
        sudo chmod 600 private_key.pem
        sudo scp -o StrictHostKeyChecking=no -i private_key.pem sunissup $USER_NAME@$HOSTNAME:/home/$USER_NAME/tmp.bin
        sudo scp -r -o StrictHostKeyChecking=no -i private_key.pem $GITHUB_WORKSPACE/static $USER_NAME@$HOSTNAME:/home/$USER_NAME/
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.IP_ADDRESS}}
        USER_NAME: ${{secrets.USER_NAME}}
      run: |      
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME '
          sudo systemctl stop sunissup
          sudo rm -rf /opt/sunissUp/sunissup
          sudo rm -rf /opt/sunissUp/static
          sudo mv /home/'$USER_NAME'/tmp.bin /opt/sunissUp/sunissup
          sudo mv /home/'$USER_NAME'/static /opt/sunissUp/
          sudo chmod +x /opt/sunissUp/sunissup
          sudo systemctl start sunissup
          echo "todo OK"
        '
