name: Compile and Deploy - Plugins Chat

on:
  push:
    branches: [ "testing", "pro" ]
    paths:
      - 'plugins/chat/**'
  workflow_dispatch:
    inputs:
      deploy_to_server:
        description: 'Deploy to server'
        required: true
        type: boolean
        default: false

jobs:
  build-and-deploy:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'

    - name: Debug Info
      working-directory: ./plugins/chat
      run: |
        pwd
        ls -la
        go version
        cat go.mod

    - name: Download dependencies
      working-directory: ./plugins/chat
      run: |
        go mod tidy

    - name: Build
      working-directory: ./plugins/chat
      run: |
        echo "Iniciando compilación..."
        sudo go build -v -buildmode=plugin -trimpath -o chat.dinamic main.go
        echo "Compilación completada"
        ls -la chat.dinamic

    - name: Deploy Chat Plugin to Server
      if: ${{ github.event_name == 'push' || github.event.inputs.deploy_to_server == 'true' }}
      env:
        PRIVATE_KEY: ${{ github.ref == 'refs/heads/pro' && secrets.SSH_PRIVATE_KEY_PRO || secrets.SSH_PRIVATE_KEY_TEST }}
        HOSTNAME: ${{ github.ref == 'refs/heads/pro' && secrets.IP_ADDRESS_PRO || secrets.IP_ADDRESS_TEST }}
        USER_NAME: ${{ secrets.USER_NAME }}
        CALLED_BY_DEPLOY_CENTER: ${{ github.event.inputs.called_by_deploy_center }}
      run: |
        echo "Desplegando en rama ${{ github.ref }} a servidor $HOSTNAME"
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem ./plugins/chat/chat.dinamic $USER_NAME@$HOSTNAME:/tmp/chat.dinamic.tmp
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME << EOF
          # Crear directorio de respaldo si no existe
          if [ ! -d "/home/$USER_NAME/backup/sunissUp/plugins" ]; then
            mkdir -p /home/$USER_NAME/backup/sunissUp/plugins
          fi
          
          # Crear copia de respaldo del plugin chat.dinamic
          cp /opt/sunissUp/plugins/chat.dinamic /home/$USER_NAME/backup/sunissUp/plugins/chat.dinamic_$(date +%Y%m%d_%H%M%S)
          
          if [[ -z "$CALLED_BY_DEPLOY_CENTER" ]]; then
            sudo systemctl stop sunissup
          fi
          
          # Verificar si el directorio existe, si no, crearlo
          if [ ! -d "/opt/sunissUp/plugins" ]; then
            sudo mkdir -p /opt/sunissUp/plugins
          fi
          
          # Mover el plugin
          sudo mv /tmp/chat.dinamic.tmp /opt/sunissUp/plugins/chat.dinamic
          
          sudo chmod +x /opt/sunissUp/plugins/chat.dinamic
          if [[ -z "$CALLED_BY_DEPLOY_CENTER" ]]; then
            sudo systemctl start sunissup
          fi
          echo "Chat Plugin desplegado correctamente."
        EOF