name: Compile and Deploy - Plugins Events

env:
  GO_VERSION: '1.23.2'

on:
  push:
    branches: [ "testing", "pro" ]
    paths:
      - 'plugins/events/**'
  workflow_dispatch:
    inputs:
      deploy_to_server:
        description: 'Deploy to server'
        required: true
        type: boolean
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Limpiar caché de Go
      run: |
        sudo rm -rf /opt/hostedtoolcache/go
        rm -rf ~/.cache/go-build
        rm -rf ~/go/pkg/mod
        echo "Caché de Go eliminado correctamente"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false

    - name: Verificar versión de Go
      run: |
        go_version=$(go version)
        echo "Versión instalada: $go_version"
        if [[ "$go_version" != *"go${{ env.GO_VERSION }}"* ]]; then
          echo "Error: Se esperaba Go ${{ env.GO_VERSION }} pero se obtuvo $go_version"
          exit 1
        fi

    - name: Debug Info
      working-directory: ./plugins/events
      run: |
        pwd
        ls -la
        go version
        cat go.mod

    - name: Download dependencies
      working-directory: ./plugins/events
      run: |
        go mod tidy

    - name: Build
      working-directory: ./plugins/events
      run: |
        echo "Iniciando compilación..."
        sudo /opt/hostedtoolcache/go/${{ env.GO_VERSION }}/x64/bin/go build -v -buildmode=plugin -trimpath -o events.dinamic main.go
        echo "Compilación completada"
        ls -la events.dinamic

    - name: Deploy Events Plugin to Server
      if: ${{ github.event_name == 'push' || github.event.inputs.deploy_to_server == 'true' }}
      env:
        PRIVATE_KEY: ${{ github.ref == 'refs/heads/pro' && secrets.SSH_PRIVATE_KEY_PRO || secrets.SSH_PRIVATE_KEY_TEST }}
        HOSTNAME: ${{ github.ref == 'refs/heads/pro' && secrets.IP_ADDRESS_PRO || secrets.IP_ADDRESS_TEST }}
        USER_NAME: ${{ secrets.USER_NAME }} 
        CALLED_BY_DEPLOY_CENTER: ${{ github.event.inputs.called_by_deploy_center }}
      run: |
        echo "Desplegando en rama ${{ github.ref }} a servidor $HOSTNAME"
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem ./plugins/events/events.dinamic $USER_NAME@$HOSTNAME:/tmp/events.dinamic.tmp
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME << EOF
          # Crear directorio de respaldo si no existe
          if [ ! -d "/home/$USER_NAME/backup/sunissUp/plugins" ]; then
            mkdir -p /home/$USER_NAME/backup/sunissUp/plugins
          fi
          
          # Crear copia de respaldo del plugin events.dinamic
          cp /opt/sunissUp/plugins/events.dinamic /home/$USER_NAME/backup/sunissUp/plugins/events.dinamic_$(date +%Y%m%d_%H%M%S)
          
          if [[ -z "$CALLED_BY_DEPLOY_CENTER" ]]; then
            sudo systemctl stop sunissup
          fi
          
          # Verificar si el directorio existe, si no, crearlo
          if [ ! -d "/opt/sunissUp/plugins" ]; then
            sudo mkdir -p /opt/sunissUp/plugins
          fi
          
          # Mover el plugin
          sudo mv /tmp/events.dinamic.tmp /opt/sunissUp/plugins/events.dinamic
          
          sudo chmod +x /opt/sunissUp/plugins/events.dinamic
          if [[ -z "$CALLED_BY_DEPLOY_CENTER" ]]; then
            sudo systemctl start sunissup
          fi
          echo "Events Plugin desplegado correctamente."
        EOF