name: Verify New Server Setup

on:
  workflow_dispatch:
    inputs:
      verbose_output:
        description: 'Mostrar salida detallada'
        type: boolean
        default: false
        required: true

jobs:
  verify-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify LDAP Installation Status
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.IP_ADDRESS }}
          USER_NAME: ${{ secrets.USER_NAME }}
          VERBOSE: ${{ inputs.verbose_output }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copiar el archivo de servicio al servidor
          scp -o StrictHostKeyChecking=no -i private_key.pem extras/sunissup.service $USER_NAME@$HOSTNAME:/tmp/

          # Primero verificamos si LDAP está instalado
          NEEDS_LDAP=$(ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME 'command -v slapd &> /dev/null; echo $?')
          
          # Si LDAP no está instalado, primero lo instalamos
          if [ "$NEEDS_LDAP" = "1" ]; then
            echo "🔍 LDAP no está instalado, procediendo con la instalación..."
            
            ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME '
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y slapd ldap-utils
            '
            
            # Después de instalar LDAP, procedemos con la configuración
            echo "🔧 Preparando archivos de configuración..."
            git clone --depth 1 https://${{ secrets.LDAP_TOKEN }}@github.com/Testing-zentinelle/zentinelle-ldap_sunissup.git ldap_config
            
            # Preparar archivos
            cd ldap_config
            tar czf ../ldap_files.tar.gz ldap/
            cd ..
            
            # Copiar archivos
            scp -o StrictHostKeyChecking=no -i private_key.pem ldap_files.tar.gz $USER_NAME@$HOSTNAME:/tmp/
            scp -o StrictHostKeyChecking=no -i private_key.pem ldap_config/default-slapd $USER_NAME@$HOSTNAME:/tmp/
          fi

          # Continuar con la verificación de servicios
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOSTNAME '
            echo "🔍 Verificando herramientas necesarias..."
            if ! command -v ss &> /dev/null; then
              echo "⚙️ Instalando iproute2..."
              sudo apt-get update
              sudo apt-get install -y iproute2
            fi

            # MariaDB Verification
            echo "🔍 Verificando MariaDB..."
            if ! command -v mariadb &> /dev/null; then
              echo "⚙️ MariaDB no está instalado. Instalando..."
              sudo apt-get update
              sudo apt-get install -y mariadb-server
              sudo systemctl start mariadb
              sudo systemctl enable mariadb
              echo "✅ MariaDB instalado correctamente"
            else
              echo "✅ MariaDB ya está instalado"
            fi

            if [ "$VERBOSE" = "true" ]; then
              echo "=== Versión de MariaDB ==="
              mariadb --version
            fi

            echo "=== Verificando estado del servicio MariaDB ==="
            if ! systemctl is-active --quiet mariadb; then
              echo "⚙️ Iniciando servicio MariaDB..."
              sudo systemctl start mariadb
              sudo systemctl enable mariadb
            fi
            echo "✅ Servicio MariaDB está activo"
            
            if [ "$VERBOSE" = "true" ]; then
              systemctl status mariadb
            fi

            echo "=== Verificando puerto MariaDB localmente ==="
            if ! ss -tuln | grep "LISTEN.*:3306" > /dev/null; then
              echo "❌ Error: Puerto 3306 no está escuchando localmente"
              exit 1
            fi
            echo "✅ Puerto 3306 está escuchando localmente"
            
            if [ "$VERBOSE" = "true" ]; then
              echo "=== Detalles del puerto 3306 ==="
              ss -tuln | grep "LISTEN.*:3306"
            fi

            # OpenLDAP Verification
            echo "🔍 Verificando OpenLDAP..."
            if command -v slapd &> /dev/null; then
              echo "✅ OpenLDAP está instalado"
              
              # Si los archivos de configuración existen en /tmp, procedemos a configurar
              if [ -f "/tmp/ldap_files.tar.gz" ] && [ -f "/tmp/default-slapd" ]; then
                echo "🔧 Configurando OpenLDAP con archivos del repositorio..."
                sudo systemctl stop slapd
                
                # Copiar default-slapd
                sudo cp /tmp/default-slapd /etc/default/slapd
                
                # Extraer y copiar archivos de configuración
                cd /tmp
                sudo tar xzf ldap_files.tar.gz
                sudo rm -rf /etc/ldap
                sudo cp -r ldap /etc/
                
                # Borrar base de datos antigua y preparar nueva
                echo "🗑️ Limpiando base de datos antigua..."
                sudo rm -rf /var/lib/ldap/*
                
                echo "📥 Importando nueva base de datos..."
                sudo slapadd -l /etc/ldap/export-default.ldif
                
                echo "🔐 Ajustando permisos..."
                sudo chown -R openldap:openldap /etc/ldap
                sudo chmod -R 750 /etc/ldap
                sudo chown -R openldap:openldap /var/lib/ldap
                sudo chmod -R 700 /var/lib/ldap
                
                # Limpiar archivos temporales
                rm -rf ldap/
                rm ldap_files.tar.gz
                rm default-slapd
              fi
            else
              echo "❌ Error: OpenLDAP no está instalado correctamente"
              exit 1
            fi

            echo "=== Verificando estado del servicio OpenLDAP ==="
            if ! systemctl is-active --quiet slapd; then
              echo "⚙️ Iniciando servicio OpenLDAP..."
              sudo systemctl start slapd
              sudo systemctl enable slapd
            fi
            echo "✅ Servicio OpenLDAP está activo"
            
            if [ "$VERBOSE" = "true" ]; then
              systemctl status slapd
            fi

            echo "=== Verificando puerto OpenLDAP localmente ==="
            if ! ss -tuln | grep "LISTEN.*:389" > /dev/null; then
              echo "❌ Error: Puerto 389 no está escuchando localmente"
              exit 1
            fi
            echo "✅ Puerto 389 está escuchando localmente"
            
            if [ "$VERBOSE" = "true" ]; then
              echo "=== Detalles del puerto 389 ==="
              ss -tuln | grep "LISTEN.*:389"
            fi

            # Configuración del servicio SunissUp
            echo "🔧 Configurando servicio SunissUp..."
            
            # Copiar el archivo de servicio a su ubicación final
            sudo cp /tmp/sunissup.service /etc/systemd/system/
            sudo rm /tmp/sunissup.service

            # Ajustar permisos del archivo de servicio
            sudo chmod 644 /etc/systemd/system/sunissup.service

            # Recargar configuración de systemd
            sudo systemctl daemon-reload

            # Habilitar el servicio para que inicie con el sistema
            sudo systemctl enable sunissup.service

            echo "✅ Servicio SunissUp configurado y habilitado (no iniciado)"
            
            if [ "$VERBOSE" = "true" ]; then
              echo "=== Estado del servicio SunissUp ==="
              systemctl status sunissup.service || true
            fi
          '
          
